kind: pipeline
name: default


type: docker
steps:
#  - name: build
#    image: maven
#    commands:
#      - mvn clean install
#      - mvn checkstyle:check
#    volumes:
#      - name: maven-repo
#        path: /root/.m2

  - name: test
    image: maven
    commands:
      - mvn help:evaluate -Dexpression=project.version -q -DforceStdout | sed -e 's,-SNAPSHOT,,g' > /root/shared/version.txt
    volumes:
      - name: shared
        path: /root/shared

  - name: tag
    image: maven
    commands:
      # Get project version
      - cat /root/shared/version.txt
      - echo $CI_TAG
#      - get version number from pom or something with bash
#      - git tag vX.Y.Z
#      - git push origin vX.Y.Z
    volumes:
      - name: shared
        path: /root/shared
    when:
      branch:
        - deploy
      event:
        - push

#  - name: publish
#    image: plugins/github-release
#    settings:
#      api_key: xxxxxxxx
#      files:
#        - dist/*
#        - bin/binary.exe
#      title: $$TAG
#      note: CHANGELOG.md
#      checksum:
#        - md5
#        - sha1
#        - sha256
#        - sha512
#        - adler32
#        - crc32
#    when:
#      event: tag
#
#  - name: docker-deploy
#    image: plugins/docker
#    settings:
#      repo: foo/bar
#      auto_tag: true
#      auto_tag_suffix: v
#      username: kevinbacon
#      password: pa55word
#    when:
#      branch:
#        - master-dummy
#      event:
#        - push


volumes:
  - name: maven-repo
    host:
      path: /root/.m2
  - name: shared
    host:
      path: /root/shared
