kind: pipeline
name: default

type: docker
steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - /home/user/.m2

  - name: build
    image: maven
    commands:
      - mvn clean install
      - mvn checkstyle:check

  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - /home/user/.m2

volumes:
  - name: cache
    host:
      path: /tmp/cache
