kind: pipeline
name: default

type: docker
steps:
  # restores the cache from a local volume
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - /drone/.m2

  - name: build
    image: maven
    environment:
      MAVEN_OPTS: -Dmaven.repo.local=/drone/.m2
    commands:
      - chmod +x ./mvnw
      - ./mvnw clean install
      - ./mvnw checkstyle:check
      - pwd
      - ls
      - ls /drone

  # rebuild the cache in case new dependencies were
  # downloaded during your build
  - name: rebuild-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      rebuild: true
      mount:
        - /drone/.m2

volumes:
  - name: cache
    host:
      path: /tmp/cache
