kind: pipeline
name: default


type: docker
steps:
#  - name: build
#    image: maven
#    commands:
#      - mvn clean install
#      - mvn checkstyle:check
#    volumes:
#      - name: maven-repo
#        path: /root/.m2

  - name: get-version
    image: maven
    commands:
      - mvn help:evaluate -Dexpression=project.version -q -DforceStdout | sed -e 's,-SNAPSHOT,,g' > /root/version
    volumes:
      - name: shared
        path: /root

  - name: tag
    image: docker:git
    commands:
      # Get project version
      - git config remote.origin.url https://ci-levimdmiller:${GIT_TOKEN}@github.com/levimdmiller/sms-bridge.git
      - git tag v`cat /root/version`
      - git push origin v`cat /root/version`
    volumes:
      - name: shared
        path: /root
    environment:
      GIT_TOKEN:
        from_secret: github_token
    when:
      branch:
        - deploy
      event:
        - push

#  - name: publish
#    image: plugins/github-release
#    settings:
#      api_key: xxxxxxxx
#      files:
#        - dist/*
#        - bin/binary.exe
#      title: $$TAG
#      note: CHANGELOG.md
#      checksum:
#        - md5
#        - sha1
#        - sha256
#        - sha512
#        - adler32
#        - crc32
#    when:
#      event: tag
#
#  - name: docker-deploy
#    image: plugins/docker
#    settings:
#      repo: foo/bar
#      auto_tag: true
#      auto_tag_suffix: v
#      username: kevinbacon
#      password: pa55word
#    when:
#      branch:
#        - master-dummy
#      event:
#        - push


volumes:
  - name: maven-repo
    host:
      path: /root/.m2
  - name: shared
    host:
      path: /root
